#!/usr/bin/env python3
"""Convert the cursor BMP sources into a C++ RGBA byte-array header."""

import argparse
from dataclasses import dataclass
import pathlib
import struct


@dataclass(frozen=True)
class Bitmap:
    width: int
    height: int
    rgba: bytes


def read_bmp(path: pathlib.Path) -> Bitmap:
    data = path.read_bytes()
    if len(data) < 54 or data[0:2] != b"BM":
        raise ValueError(f"{path} is not a Windows bitmap")

    pixel_offset = struct.unpack_from("<I", data, 10)[0]
    dib_size = struct.unpack_from("<I", data, 14)[0]
    width = struct.unpack_from("<i", data, 18)[0]
    stored_height = struct.unpack_from("<i", data, 22)[0]
    planes = struct.unpack_from("<H", data, 26)[0]
    bits_per_pixel = struct.unpack_from("<H", data, 28)[0]
    compression = struct.unpack_from("<I", data, 30)[0]

    if dib_size < 40 or planes != 1 or width <= 0 or stored_height == 0:
        raise ValueError(f"{path} has unsupported bitmap dimensions or headers")
    if bits_per_pixel != 32:
        raise ValueError(f"{path} must be a 32-bit bitmap")
    if compression != 0:
        raise ValueError(f"{path} must be an uncompressed bitmap")

    height = abs(stored_height)
    row_bytes = width * 4
    required_size = pixel_offset + row_bytes * height
    if required_size > len(data):
        raise ValueError(f"{path} has truncated pixel data")

    rgba = bytearray()
    stored_top_down = stored_height < 0
    for output_y in range(height):
        stored_y = output_y if stored_top_down else height - 1 - output_y
        row_offset = pixel_offset + stored_y * row_bytes
        for x in range(width):
            blue, green, red, alpha = data[
                row_offset + x * 4 : row_offset + x * 4 + 4
            ]
            rgba.extend((red, green, blue, alpha))

    return Bitmap(width, height, bytes(rgba))


def _format_bytes(name: str, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16])
        rows.append(f"  {values},")
    return f"inline constexpr std::uint8_t {name}[] = {{\n" + "\n".join(rows) + "\n};"


def generate_header(open_path: pathlib.Path, closed_path: pathlib.Path) -> str:
    open_bitmap = read_bmp(open_path)
    closed_bitmap = read_bmp(closed_path)
    if (open_bitmap.width, open_bitmap.height) != (
        closed_bitmap.width,
        closed_bitmap.height,
    ):
        raise ValueError("open and closed cursor bitmaps must have matching dimensions")
    if (open_bitmap.width, open_bitmap.height) != (32, 32):
        raise ValueError("cursor bitmaps must be exactly 32x32 pixels")

    return "\n".join(
        (
            "// Generated by scripts/embed_cursor_assets.py. Do not edit.",
            "#pragma once",
            "",
            "#include <cstdint>",
            "",
            "namespace paper_cursor_assets {",
            f"inline constexpr int CURSOR_WIDTH = {open_bitmap.width};",
            f"inline constexpr int CURSOR_HEIGHT = {open_bitmap.height};",
            "",
            _format_bytes("OPEN_HAND_RGBA", open_bitmap.rgba),
            "",
            _format_bytes("CLOSED_HAND_RGBA", closed_bitmap.rgba),
            "} // namespace paper_cursor_assets",
            "",
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--open", type=pathlib.Path, required=True)
    parser.add_argument("--closed", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()

    generated = generate_header(args.open, args.closed)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
        args.output.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
